spring.application.name=due-diligence-agent

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/real_estate_db
spring.datasource.username=postgres
spring.datasource.password=knmdp

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

jwt.secret=MySuperSecretKeyForJwtAuthentication123456789012345678901234567890
jwt.expiration=3600000

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE