spring.application.name=due-diligence-agent

# ==========================
# Database Configuration
# ==========================
spring.datasource.url=jdbc:postgresql://localhost:5432/real_estate_db
spring.datasource.username=postgres
spring.datasource.password=knmdp

# ==========================
# JPA Configuration
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# Server
# ==========================
server.port=8080

# ==========================
# JWT Configuration
# ==========================
jwt.secret=MySuperSecretKeyForJwtAuthentication123456789012345678901234567890
jwt.expiration=3600000

# ==========================
# Hibernate Logging
# ==========================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ==========================
# Spring MVC Logging
# ==========================
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

# ==========================
# Email Configuration
# ==========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bundummy420@gmail.com
spring.mail.password=cosviixvsdexunwu

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true