spring.application.name=due-diligence-agent

# ==========================
# Database Configuration
# ==========================
spring.datasource.url=jdbc:postgresql://localhost:5432/real_estate_db
spring.datasource.username=postgres
spring.datasource.password=K@ustuk.121

# ==========================
# JPA Configuration
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# Server Configuration
# ==========================
server.port=8080

# ==========================
# JWT Configuration
# ==========================
jwt.secret=dsF+8c9sEWPInYLhAIbrNidHtVoB0g5cNx6PGEwTFd4Iolg9qrz7oIUwiBM44yUQC1DnXa54XRK05srlvr/FyA==
jwt.expiration=3600000

# ==========================
# Logging
# ==========================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

# ==========================
# Gmail SMTP Configuration
# ==========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=astitvarajfbg@gmail.com
spring.mail.password=luen xlll lifx wmlb

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

google.client.id=520450322801-uksrpeu3m2hgkc9pqp1lhj64fo9dioro.apps.googleusercontent.com